# This file is used as a template for automatic generation of 'flavor' sample configurations.

external_components:
  # source: github://krahabb/esphome # development repo
  source: github://krahabb/esphome-victron-vedirect

uart:
  - id: uart_0
    tx_pin: GPIO4
    rx_pin: GPIO5
    baud_rate: 19200
    rx_buffer_size: 256

m3_vedirect:
  - id: vedirect_0
    uart_id: uart_0
    name: "Victron"
    flavor: [ALL]
    textframe:
      auto_create_entities: false
    hexframe:
      auto_create_entities: false
      ping_timeout: 2min

binary_sensor:
  - platform: m3_vedirect
    vedirect_id: vedirect_0
    vedirect_entities:
      - type: LOAD_OUTPUT_STATE
        name: "LOAD_OUTPUT_STATE"

number:
  - platform: m3_vedirect
    vedirect_id: vedirect_0
    vedirect_entities:
      - type: AC_OUT_VOLTAGE_SETPOINT
        name: "AC_OUT_VOLTAGE_SETPOINT"
      - type: ALARM_LOW_VOLTAGE_SET
        name: "ALARM_LOW_VOLTAGE_SET"
      - type: ALARM_LOW_VOLTAGE_CLEAR
        name: "ALARM_LOW_VOLTAGE_CLEAR"
      - type: SHUTDOWN_LOW_VOLTAGE_SET
        name: "SHUTDOWN_LOW_VOLTAGE_SET"

select:
  - platform: m3_vedirect
    vedirect_id: vedirect_0
    vedirect_entities:
      - type: DEVICE_MODE
        name: "DEVICE_MODE"
      - type: RELAY_MODE
        name: "RELAY_MODE"

sensor:
  - platform: m3_vedirect
    vedirect_id: vedirect_0
    vedirect_entities:
      - type: TTG
        name: "TTG"
      - type: SOC
        name: "SOC"
      - type: AC_OUT_VOLTAGE
        name: "AC_OUT_VOLTAGE"
      - type: AC_OUT_CURRENT
        name: "AC_OUT_CURRENT"
      - type: AC_OUT_APPARENT_POWER
        name: "AC_OUT_APPARENT_POWER"
      - type: VOLTAGE_RANGE_MIN
        name: "VOLTAGE_RANGE_MIN"
      - type: VOLTAGE_RANGE_MAX
        name: "VOLTAGE_RANGE_MAX"
      - type: DC_CHANNEL1_VOLTAGE
        name: "DC_CHANNEL1_VOLTAGE"
      - type: DC_CHANNEL1_POWER
        name: "DC_CHANNEL1_POWER"
      - type: DC_CHANNEL1_CURRENT
        name: "DC_CHANNEL1_CURRENT"
      - type: LOAD_CURRENT
        name: "LOAD_CURRENT"
      - type: PANEL_MAXIMUM_VOLTAGE
        name: "PANEL_MAXIMUM_VOLTAGE"
      - type: PANEL_VOLTAGE
        name: "PANEL_VOLTAGE"
      - type: PANEL_POWER
        name: "PANEL_POWER"
      - type: PANEL_CURRENT
        name: "PANEL_CURRENT"
      - type: MAXIMUM_POWER_YESTERDAY
        name: "MAXIMUM_POWER_YESTERDAY"
      - type: YIELD_YESTERDAY
        name: "YIELD_YESTERDAY"
      - type: MAXIMUM_POWER_TODAY
        name: "MAXIMUM_POWER_TODAY"
      - type: YIELD_TODAY
        name: "YIELD_TODAY"
      - type: CHARGER_VOLTAGE
        name: "CHARGER_VOLTAGE"
      - type: CHARGER_CURRENT
        name: "CHARGER_CURRENT"
      - type: USER_YIELD
        name: "USER_YIELD"
      - type: SYSTEM_YIELD
        name: "SYSTEM_YIELD"
      - type: BAT_TEMPERATURE
        name: "BAT_TEMPERATURE"
      - type: DC_MONITOR_MODE
        name: "DC_MONITOR_MODE"

switch:
  - platform: m3_vedirect
    vedirect_id: vedirect_0
    vedirect_entities:
      - type: RELAY_CONTROL
        name: "RELAY_CONTROL"
      - type: ALARM_BUZZER
        name: "ALARM_BUZZER"

text_sensor:
  - platform: m3_vedirect
    vedirect_id: vedirect_0
    vedirect_entities:
      - type: BLE_MODE
        name: "BLE_MODE"
      - type: PRODUCT_ID
        name: "PRODUCT_ID"
      - type: APP_VER
        name: "APP_VER"
      - type: SERIAL_NUMBER
        name: "SERIAL_NUMBER"
      - type: MODEL_NAME
        name: "MODEL_NAME"
      - type: CAPABILITIES
        name: "CAPABILITIES"
      - type: CAPABILITIES_BLE
        name: "CAPABILITIES_BLE"
      - type: DEVICE_STATE
        name: "DEVICE_STATE"
      - type: DEVICE_OFF_REASON
        name: "DEVICE_OFF_REASON"
      - type: DEVICE_OFF_REASON_2
        name: "DEVICE_OFF_REASON_2"
      - type: WARNING_REASON
        name: "WARNING_REASON"
      - type: ALARM_REASON
        name: "ALARM_REASON"
      - type: MPPT_TRACKER_MODE
        name: "MPPT_TRACKER_MODE"
      - type: CHR_ERROR_CODE
        name: "CHR_ERROR_CODE"
